### PR TITLE
Changed the path url encoding so that is should work with special chars ...

### PR DESCRIPTION
**Pull request by 72quadrat**
...like german umlauts and such...

new: $path = str_replace('%2F', '/', urlencode($path));

### CODE REVIEW

**Comment by jimdoescode** [comment]
Have you confirmed that having spaces encoded with '+' as urlencode does works?

**Comment by 72quadrat** [comment]
OOps,... nope they don't :-(

**Comment by 72quadrat** [comment]
Should be rawurlencode no urlencode

**Comment by jimdoescode** [comment]
OK I'll close this one. Just open a new one with rawurlencode.

**Comment by 72quadrat** [comment]
did it sorry

**Comment by jimdoescode** [comment]
I haven't gotten the new pull request yet. Did you create a new one?

**Comment by 72quadrat** [comment]
Yes, i have it, and on github i've Seen it also. I'm now out for the Summer, Best, Timo

.
.
.
.
.
Timo Höner
.
mail@timohoener.de
72quadrat.de
.
Mobil 01796786881
Festnetz 03067
Gabriel Max Straße 4
10245 Berlin

Am 12.05.2012 um 18:39 schrieb Jimreply@reply.github.com:

**Comment by jimdoescode** [comment]
Hmm the changes don't seem to be reflected in this pull request and I haven't received notice of a new one. I'll just update it myself and close this request. Thanks for the fix.

**Comment by jimdoescode** [comment]
Oh never mind it just showed up. Github is acting weird. OK Thanks.

**Pull request merged**
